SELECT a.REST_ID, a.REST_NAME, a.FOOD_TYPE, a.FAVORITES, a.ADDRESS, ROUND(AVG(b.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS a 
INNER JOIN REST_REVIEW AS b ON a.REST_ID = b.REST_ID
WHERE a.ADDRESS LIKE "서울%"
GROUP BY REST_NAME
ORDER BY SCORE DESC, a.FAVORITES DESC


/*
SELECT 리뷰 평균점수는 소수점 세 번째 자리에서 반올림 ROUND(AVG(),2)
FROM REST_ID로 조인
WHERE 서울 위치
GROUB BY 식당 이름 별로 그룹화
HAVING 평균 점수 
ORDER BY 평균점수, 즐겨찾기 수 내림차순
*/