SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, GENDER, COUNT(DISTINCT ui.USER_ID) USERS
FROM USER_INFO ui
JOIN ONLINE_SALE os
ON ui.USER_ID = os.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER

/*
년, 월, 성별 별로 상품을 구매한 회원수를 집계
결과는 년, 월, 성별을 기준으로 오름차순 정렬

- GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER

성별 정보가 없는 경우 결과에서 제외 (GENDER IS NOT NULL)
*/